spring.application.name=api

spring.datasource.url=jdbc:postgresql://localhost:5432/SusluTaslar
spring.datasource.username=postgres
spring.datasource.password=${DB_PASSWORD}
spring.jpa.hibernate.ddl-auto=update
jwt.secret=${JWT_SECRET}